# Generated by Django 4.2.1 on 2023-05-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresas',
            old_name='description',
            new_name='Cnpj',
        ),
        migrations.AlterField(
            model_name='empresas',
            name='active',
            field=models.CharField(choices=[('Inactive', 'Não'), ('Active', 'Sim')], max_length=8),
        ),
    ]
